=== NguyenThanhLanh/XML_Technology/KiemTraSo2/NguyenThanhLanh_61133851_KiemTraSo2/QLMS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="QLMS">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="TheLoais" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="TheLoai" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="MaTL" minOccurs="1" maxOccurs="1" >
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[0-9]{2}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="TenTL" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Sachs" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Sach" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="MaSach" >
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Z][0-9]{5}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="TenSach" minOccurs="1" maxOccurs="1" type="xs:string"/>
                                        <xs:element name="TacGia" minOccurs="1" maxOccurs="1" type="xs:string"/>
                                        <xs:element name="MaTL" minOccurs="1" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[0-9]{2}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="TheDocGias" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="TheDocGia" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="MaThe" minOccurs="1" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="PM[0-9]{4}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="TenDG" minOccurs="1" maxOccurs="1" type="xs:string"/>
                                        <xs:element name="DiaChi" minOccurs="1" maxOccurs="1" type="xs:string"/>
                                        <xs:element name="NgayCap" minOccurs="1" maxOccurs="1" type="xs:date"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ChiTietMuons" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ChiTietMuon" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="MaThe" minOccurs="1" maxOccurs="1" >
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="PM[0-9]{4}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element> 
                                        <xs:element name="MaSach" minOccurs="1" maxOccurs="1" >
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Z][0-9]{5}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="NgayMuon" minOccurs="1" maxOccurs="1" type="xs:date"/>
                                        <xs:element name="NgayTra" minOccurs="0" maxOccurs="1" type="xs:date"/>
                                        <xs:element name="TaiCho">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Về nhà"/>
                                                    <xs:enumeration value="Tại chỗ"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="LePhis" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="LePhi" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="MaThe" minOccurs="1" maxOccurs="1" >
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="PM[0-9]{4}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Nam" minOccurs="1" maxOccurs="1" type="xs:integer" />
                                        <xs:element name="LePhi" minOccurs="1" maxOccurs="1" type="xs:integer"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="TheLoai_Key">
            <xs:selector xpath="TheLoai"/>
            <xs:field xpath="MaTL"/>
        </xs:key>
        <xs:key name="Sach_Key">
            <xs:selector xpath="Sach"/>
            <xs:field xpath="MaSach"/>
        </xs:key>
        <xs:key name="TheDocGia_Key">
            <xs:selector xpath="TheDocGia"/>
            <xs:field xpath="MaThe"/>
        </xs:key>
        <xs:key name="ChiTietMuon_Key">
            <xs:selector xpath="ChiTietMuon"/>
            <xs:field xpath="MaThe"/>
            <xs:field xpath="MaSach"/>
            <xs:field xpath="NgayMuon"/>
        </xs:key>
        <xs:key name="LePhi_Key">
            <xs:selector xpath="MaThe"/>
            <xs:field xpath="Nam"/>
        </xs:key>
        <xs:keyref name="Sach_TL_Key" refer="TheLoai_Key">
            <xs:selector xpath="Sach"/>
            <xs:field xpath="MaTL"/>
        </xs:keyref>
        <xs:keyref name="CTMuon_DocGia_Key" refer="TheDocGia_Key">
            <xs:selector xpath="ChiTietMuon"/>
            <xs:field xpath="MaThe"/>
        </xs:keyref>
        <xs:keyref name="CTMuon_Sach" refer="Sach_Key">
            <xs:selector xpath="ChiTietMuon"/>
            <xs:field xpath="MaSach"/>
        </xs:keyref>
        <xs:keyref name="LePhi_DocGia_Key" refer="TheDocGia_Key">
            <xs:selector xpath="LePhi"/>
            <xs:field xpath="MaThe"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== NguyenThanhLanh/XML_Technology/KiemTraSo2/NguyenThanhLanh_61133851_KiemTraSo2/QLMS.xml
<?xml version="1.0" encoding="UTF-8"?>
<QLMS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="QLMS.xsd">
    <TheLoais>
        <TheLoai>
            <MaTL>01</MaTL>
            <TenTL>Văn học nghệ thuật</TenTL>
        </TheLoai>
        <TheLoai>
            <MaTL>02</MaTL>
            <TenTL>Khoa học kỹ thuật</TenTL>
        </TheLoai>
        <TheLoai>
            <MaTL>03</MaTL>
            <TenTL>Công nghệ thông tin</TenTL>
        </TheLoai>
        <TheLoai>
            <MaTL>04</MaTL>
            <TenTL>Công nghệ hóa học</TenTL>
        </TheLoai>
        <TheLoai>
            <MaTL>05</MaTL>
            <TenTL>Đạo làm người</TenTL>
        </TheLoai>
    </TheLoais>
    <Sachs>
        <Sach>
            <MaSach>A10101</MaSach>
            <TenSach>Giáo Trình CSDL</TenSach>
            <TacGia>Đinh Mạnh Tường</TacGia>
            <MaTL>03</MaTL>
        </Sach>
        <Sach>
            <MaSach>B10219</MaSach>
            <TenSach>Giáo trình tin học ứng dụng</TenSach>
            <TacGia>Trần Công Minh</TacGia>
            <MaTL>03</MaTL>
        </Sach>
        <Sach>
            <MaSach>C10084</MaSach>
            <TenSach>Cơ sở Thông Tin</TenSach>
            <TacGia>Nguyễn Thành Lãnh</TacGia>
            <MaTL>02</MaTL>
        </Sach>
        <Sach>
            <MaSach>D00573</MaSach>
            <TenSach>Cafe cùng Tony</TenSach>
            <TacGia>Emploment</TacGia>
            <MaTL>01</MaTL>
        </Sach>
        <Sach>
            <MaSach>F09807</MaSach>
            <TenSach>Tạp chí thời trang</TenSach>
            <TacGia>Cao Văn La</TacGia>
            <MaTL>04</MaTL>
        </Sach>
    </Sachs>
    <TheDocGias>
        <TheDocGia>
            <MaThe>PM0001</MaThe>
            <TenDG>Nguyễn Thành Lãnh</TenDG>
            <DiaChi>Nha Trang, Khánh Hòa</DiaChi>
            <NgayCap>2019-09-02</NgayCap>
        </TheDocGia>
        <TheDocGia>
            <MaThe>PM0002</MaThe>
            <TenDG>Nguyễn Thành Chung</TenDG>
            <DiaChi>Nha Trang, Khánh Hòa</DiaChi>
            <NgayCap>2019-09-02</NgayCap>
        </TheDocGia>
        <TheDocGia>
            <MaThe>PM0003</MaThe>
            <TenDG>Nguyễn Thành Chung</TenDG>
            <DiaChi>Nha Trang, Khánh Hòa</DiaChi>
            <NgayCap>2019-09-02</NgayCap>
        </TheDocGia>
        <TheDocGia>
            <MaThe>PM0004</MaThe>
            <TenDG>Nguyễn Thành Chung</TenDG>
            <DiaChi>Nha Trang, Khánh Hòa</DiaChi>
            <NgayCap>2019-09-02</NgayCap>
        </TheDocGia>
        <TheDocGia>
            <MaThe>PM0005</MaThe>
            <TenDG>Nguyễn Thành Chung</TenDG>
            <DiaChi>Nha Trang, Khánh Hòa</DiaChi>
            <NgayCap>2019-09-02</NgayCap>
        </TheDocGia>
    </TheDocGias>
    <ChiTietMuons>
        <ChiTietMuon>
            <MaThe>PM0005</MaThe>
            <MaSach>D00573</MaSach>
            <NgayMuon>2012-03-01</NgayMuon>
            <TaiCho>Về nhà</TaiCho>
        </ChiTietMuon>
        <ChiTietMuon>
            <MaThe>PM0005</MaThe>
            <MaSach>D00573</MaSach>
            <NgayMuon>2012-03-02</NgayMuon>
            <NgayTra>2012-03-29</NgayTra>
            <TaiCho>Về nhà</TaiCho>
        </ChiTietMuon>
        <ChiTietMuon>
            <MaThe>PM0005</MaThe>
            <MaSach>D00573</MaSach>
            <NgayMuon>2012-03-03</NgayMuon>
            <NgayTra>2012-03-20</NgayTra>
            <TaiCho>Về nhà</TaiCho>
        </ChiTietMuon>
        <ChiTietMuon>
            <MaThe>PM0005</MaThe>
            <MaSach>D00573</MaSach>
            <NgayMuon>2012-03-04</NgayMuon>
            <TaiCho>Về nhà</TaiCho>
        </ChiTietMuon>
        <ChiTietMuon>
            <MaThe>PM0005</MaThe>
            <MaSach>D00573</MaSach>
            <NgayMuon>2012-03-05</NgayMuon>
            <TaiCho>Về nhà</TaiCho>
        </ChiTietMuon>
        
    </ChiTietMuons>
    <LePhis>
        <LePhi>
            <MaThe>PM0001</MaThe>
            <Nam>2001</Nam>
            <LePhi>8000</LePhi>
        </LePhi>
        <LePhi>
            <MaThe>PM0001</MaThe>
            <Nam>2002</Nam>
            <LePhi>8000</LePhi>
        </LePhi>
        <LePhi>
            <MaThe>PM0001</MaThe>
            <Nam>2003</Nam>
            <LePhi>8000</LePhi>
        </LePhi>
        <LePhi>
            <MaThe>PM0001</MaThe>
            <Nam>2004</Nam>
            <LePhi>8000</LePhi>
        </LePhi>
        <LePhi>
            <MaThe>PM0001</MaThe>
            <Nam>2005</Nam>
            <LePhi>8000</LePhi>
        </LePhi>
    </LePhis>
</QLMS>
