=== NguyenThanhLanh/XML_Technology/BTChuong4_Schema/BT6/Bai6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="QLBH">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MatHang" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="InventoryID">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z]{1}[0-9]{5}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Unit_Price">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minInclusive value="1"></xs:minInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Stock_Bin">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="B[0-9]{3}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== NguyenThanhLanh/XML_Technology/BTChuong4_Schema/BT6/Test_BT6.xml
<?xml version="1.0" encoding="UTF-8"?>
<QLBH xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/D:/CongNghe_XML_VaUngDung/BTChuong4/Bai6.xsd">
    <MatHang>
        <Name>paper</Name>
        <InventoryID>F12333</InventoryID>
        <Unit_Price>1.22</Unit_Price>
        <Stock_Bin>B789</Stock_Bin>
    </MatHang>
    <MatHang>
        <Name>clips</Name>
        <InventoryID>Z55557</InventoryID>
        <Unit_Price>22.33</Unit_Price>
        <Stock_Bin>B123</Stock_Bin>
    </MatHang>
</QLBH>
