=== NguyenThanhLanh/XML_Technology/BTChuong4_Schema/BT5/Bai5_rework.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="QLDiemDanh">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Lop" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaLop">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9]{2}[A-Z]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="DateTime" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="DSSVVang" maxOccurs="1" minOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="SinhVien" maxOccurs="unbounded"
                                                  minOccurs="0">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="MSSV">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:pattern value="[0-9]{8}"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                  <xs:element name="HoVaTen" type="xs:string"/>
                                                  <xs:element name="SoLanVang"
                                                  type="xs:unsignedByte"/>
                                                  <xs:element name="LyDoVang" type="xs:string"/>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="Month"/>
                                    <xs:attribute name="Year"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== NguyenThanhLanh/XML_Technology/BTChuong4_Schema/BT5/Test_BT5.xml
<?xml version="1.0" encoding="UTF-8"?>
<QLDiemDanh xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/D:/CongNghe_XML_VaUngDung/BTChuong4/Bai5_rework.xsd">
    <Lop>
        <MaLop>56TH</MaLop>
        <DateTime Month="3" Year="2017">
            <DSSVVang>
                <SinhVien>
                    <MSSV>56160342</MSSV>
                    <HoVaTen>Khuong Huu Duc</HoVaTen>
                    <SoLanVang>3</SoLanVang>
                    <LyDoVang>Khong ly do</LyDoVang>
                </SinhVien>
                <SinhVien>
                    <MSSV>56234980</MSSV>
                    <HoVaTen>Le Thi Hien</HoVaTen>
                    <SoLanVang>2</SoLanVang>
                    <LyDoVang>Benh</LyDoVang>
                </SinhVien>
            </DSSVVang>
        </DateTime>
    </Lop>
</QLDiemDanh>
