=== NguyenThanhLanh/XML_Technology/BTChuong4_Schema/BT2/QLBH.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="QLBH">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MatHang" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaMH">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z]{2}[0-9]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TenMH" type="xs:string"/>
                            <xs:element name="DonGia" type="xs:unsignedInt"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="HoaDon" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaHD">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[H][D][0-9]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MaKhachHang">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z]{2}[0-9]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TenKhachHang" type="xs:string"/>
                            <xs:element name="DiaChi">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9]*[a-zA-Z]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="DSMatHangMua">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="MaMH">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:pattern value="[0-9]*[xs:string]"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="TenMH" type="xs:string"/>
                                        <xs:element name="SoLuong" type="xs:unsignedInt"/>
                                        <xs:element name="DonGia" type="xs:unsignedInt"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="Key_MatHang">
            <xs:selector xpath="MatHang"/>
            <xs:field xpath="MaMH"/>
        </xs:key>
        <xs:keyref name="Key_DSMH_MH" refer="Key_MatHang">
            <xs:selector xpath="DSMatHangMua"/>
            <xs:field xpath="MaMH"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== NguyenThanhLanh/XML_Technology/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<QLBH xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/CongNghe_XML_VaUngDung/QLBH.xsd">
    <MatHang>
        <MaMH>AA00</MaMH>
        <TenMH>TenMH0</TenMH>
        <DonGia>214748364</DonGia>
    </MatHang>
    <MatHang>
        <MaMH>AA00</MaMH>
        <TenMH>TenMH1</TenMH>
        <DonGia>214748364</DonGia>
    </MatHang>
    <HoaDon>
        <MaHD>HD00</MaHD>
        <MaKhachHang>AA00</MaKhachHang>
        <TenKhachHang>TenKhachHang0</TenKhachHang>
        <DiaChi>A</DiaChi>
        <DSMatHangMua>
            <MaMH>:</MaMH>
            <TenMH>TenMH2</TenMH>
            <SoLuong>214748364</SoLuong>
            <DonGia>214748364</DonGia>
        </DSMatHangMua>
    </HoaDon>
    <HoaDon>
        <MaHD>HD00</MaHD>
        <MaKhachHang>AA00</MaKhachHang>
        <TenKhachHang>TenKhachHang1</TenKhachHang>
        <DiaChi>A</DiaChi>
        <DSMatHangMua>
            <MaMH>:</MaMH>
            <TenMH>TenMH3</TenMH>
            <SoLuong>214748364</SoLuong>
            <DonGia>214748364</DonGia>
        </DSMatHangMua>
    </HoaDon>
</QLBH>
