=== NguyenThanhLanh/XML_Technology/BTChuong7_XSLT/BT2/SinhVien.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="QLSV">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="SinhVien" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaSV" minOccurs="1" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="sv[0-9]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TenSV" minOccurs="1" maxOccurs="1" type="xs:string"/>
                            <xs:element name="GioiTinh" minOccurs="1" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Nam"></xs:enumeration>
                                        <xs:enumeration value="Ná»¯"></xs:enumeration>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="NgaySinh" minOccurs="1" maxOccurs="1" type="xs:date"/>
                            <xs:element name="MaLop" minOccurs="1" maxOccurs="1" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Lop" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaLop" minOccurs="1" maxOccurs="1" type="xs:string"/>
                            <xs:element name="TenLop" minOccurs="1" maxOccurs="1" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="SV_Key">
            <xs:selector xpath="SinhVien"/>
            <xs:field xpath="MaSV"/>
        </xs:key>
        <xs:key name="Lop_key">
            <xs:selector xpath="Lop"/>
            <xs:field xpath="MaLop"/>
        </xs:key>
        <xs:keyref name="SV_LOP_key" refer="Lop_key">
            <xs:selector xpath="SinhVien"/>
            <xs:field xpath="MaLop"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== NguyenThanhLanh/XML_Technology/BTChuong7_XSLT/BT2/SinhVien.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../BT2/QLSV.xsl"?>
<QLSV xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/D:/CongNghe_XML_VaUngDung/BTChuong7_XSLT/BT2/SinhVien.xsd">
    <SinhVien>
        <MaSV>sv01</MaSV>
        <TenSV>Phan Tuấn Cường</TenSV>
        <GioiTinh>Nam</GioiTinh>
        <NgaySinh>1993-03-03</NgaySinh>
        <MaLop>CNTT16</MaLop>
    </SinhVien>
    <SinhVien>
        <MaSV>sv02</MaSV>
        <TenSV>Huỳnh Chí Tâm</TenSV>
        <GioiTinh>Nam</GioiTinh>
        <NgaySinh>1993-03-08</NgaySinh>
        <MaLop>CNTT16</MaLop>
    </SinhVien>
    <SinhVien>
        <MaSV>sv03</MaSV>
        <TenSV>Vương Chí Dũng</TenSV>
        <GioiTinh>Nam</GioiTinh>
        <NgaySinh>1991-04-14</NgaySinh>
        <MaLop>CNTT16</MaLop>
    </SinhVien>
    <SinhVien>
        <MaSV>sv04</MaSV>
        <TenSV>Phạm Đức Nguyên</TenSV>
        <GioiTinh>Nam</GioiTinh>
        <NgaySinh>1993-07-27</NgaySinh>
        <MaLop>TCKT15</MaLop>
    </SinhVien>
    <SinhVien>
        <MaSV>sv05</MaSV>
        <TenSV>Trương Mỹ Yến Nhi</TenSV>
        <GioiTinh>Nữ</GioiTinh>
        <NgaySinh>1993-10-03</NgaySinh>
        <MaLop>TCKT15</MaLop>
    </SinhVien>
    <Lop>
        <MaLop>CNTT16</MaLop>
        <TenLop>Công nghệ thông tin 2017</TenLop>
    </Lop>
    <Lop>
        <MaLop>TCKT15</MaLop>
        <TenLop>Tài chính kế toán 15</TenLop>
    </Lop>
</QLSV>
