=== NguyenThanhLanh/XML_Technology/KiemTraSo2/KiemTraSo2_Nguyen Thanh Lanh_61133851/QLMS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="QLMS">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="TheLoai" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaTL">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TenTL" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Sach" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaSach">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9]{6}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TenSach" type="xs:string"/>
                            <xs:element name="TacGia" type="xs:string"/>
                            <xs:element name="MaTL" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="TheDocGia" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaThe">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9]{6}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TenDG" type="xs:string"/>
                            <xs:element name="DiaChi" type="xs:string"/>
                            <xs:element name="NgayCap" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ChiTietMuon" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaThe" type="xs:string"/>
                            <xs:element name="MaSach" type="xs:string"/>
                            <xs:element name="NgayMuon" type="xs:date"/>                            
                            <xs:element name="NgayTra" minOccurs="0" maxOccurs="1" type="xs:date">
                            </xs:element>
                            <xs:element name="TaiCho">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Tại chỗ"/>
                                        <xs:enumeration value="Về nhà"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="LePhi" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaThe" type="xs:string"/>
                            <xs:element name="Nam" type="xs:integer"/>
                            <xs:element name="LePhi" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="TheLoaiKey">
            <xs:selector xpath="TheLoai"/>
            <xs:field xpath="MaTL"/>
        </xs:key>
        <xs:key name="SachKey">
            <xs:selector xpath="Sach"/>
            <xs:field xpath="MaSach"/>
        </xs:key>
        <xs:key name="TheDocGiaKey">
            <xs:selector xpath="TheDocGia"/>
            <xs:field xpath="MaThe"/>
        </xs:key>
        <xs:key name="ChiTietMuonKey">
            <xs:selector xpath="ChiTietMuon"/>
            <xs:field xpath="MaThe"/>
            <xs:field xpath="MaSach"/>
            <xs:field xpath="NgayMuon"/>
        </xs:key>
        <xs:keyref name="CTM_TDGKeyRef" refer="TheDocGiaKey">
            <xs:selector xpath="ChiTietMuon"/>
            <xs:field xpath="MaThe"/>
        </xs:keyref>
        <xs:keyref name="CTM_SachKeyRef" refer="SachKey">
            <xs:selector xpath="ChiTietMuon"/>
            <xs:field xpath="MaSach"/>
        </xs:keyref>
        <xs:key name="LePhiKey">
            <xs:selector xpath="LePhi"/>
            <xs:field xpath="MaThe"/>
            <xs:field xpath="Nam"/>
        </xs:key>
        <xs:keyref name="LePhi_TDGKeyRef" refer="TheDocGiaKey">
            <xs:selector xpath="LePhi"/>
            <xs:field xpath="MaThe"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== NguyenThanhLanh/XML_Technology/KiemTraSo2/KiemTraSo2_Nguyen Thanh Lanh_61133851/QLMS.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="QLMS.xsl"?>
<QLMS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/XML/BTXML/OnTapXML/KtraMau1/QLMS.xsd">
    <TheLoai>
        <MaTL>01</MaTL>
        <TenTL>Khoa học và đời sống</TenTL>
    </TheLoai>
    <TheLoai>
        <MaTL>02</MaTL>
        <TenTL>Công nghệ thông tin</TenTL>
    </TheLoai>
    <TheLoai>
        <MaTL>03</MaTL>
        <TenTL>Thế giới hoang dã</TenTL>
    </TheLoai>
    <TheLoai>
        <MaTL>04</MaTL>
        <TenTL>Tình cảm</TenTL>
    </TheLoai>
    <TheLoai>
        <MaTL>05</MaTL>
        <TenTL>Kỹ năng sống</TenTL>
    </TheLoai>
    
    <Sach>
        <MaSach>A10101</MaSach>
        <TenSach>Công nghệ thông tin</TenSach>
        <TacGia>ĐHNT</TacGia>
        <MaTL>05</MaTL>
    </Sach>
    <Sach>
        <MaSach>A10102</MaSach>
        <TenSach>Cafe cùng Tony</TenSach>
        <TacGia>John</TacGia>
        <MaTL>02</MaTL>
    </Sach>
    <Sach>
        <MaSach>A10103</MaSach>
        <TenSach>Không quan tâm</TenSach>
        <TacGia>Thiếu niên</TacGia>
        <MaTL>04</MaTL>
    </Sach>
    <Sach>
        <MaSach>A10104</MaSach>
        <TenSach>Cái quần</TenSach>
        <TacGia>Mark</TacGia>
        <MaTL>01</MaTL>
    </Sach>
    <Sach>
        <MaSach>A10105</MaSach>
        <TenSach>Cái áo</TenSach>
        <TacGia>Thiếu niên</TacGia>
        <MaTL>03</MaTL>
    </Sach>
    
    <TheDocGia>
        <MaThe>PM0001</MaThe>
        <TenDG>Chí Phèo</TenDG>
        <DiaChi>Nha Trang</DiaChi>
        <NgayCap>2021-04-03</NgayCap>
    </TheDocGia>
    <TheDocGia>
        <MaThe>PM0002</MaThe>
        <TenDG>Tố Hữu</TenDG>
        <DiaChi>Ninh Hòa</DiaChi>
        <NgayCap>2021-04-09</NgayCap>
    </TheDocGia>
    <TheDocGia>
        <MaThe>PM0003</MaThe>
        <TenDG>Nam Cao</TenDG>
        <DiaChi>Ninh Thượng</DiaChi>
        <NgayCap>2021-05-03</NgayCap>
    </TheDocGia>
    <TheDocGia>
        <MaThe>PM0004</MaThe>
        <TenDG>Mít</TenDG>
        <DiaChi>Nha Trang</DiaChi>
        <NgayCap>2021-04-13</NgayCap>
    </TheDocGia>
    <TheDocGia>
        <MaThe>PM0005</MaThe>
        <TenDG>Cao Văn Cầu</TenDG>
        <DiaChi>Ninh Sim</DiaChi>
        <NgayCap>2019-12-03</NgayCap>
    </TheDocGia>
    
    <ChiTietMuon>
        <MaThe>PM0005</MaThe>
        <MaSach>A10103</MaSach>
        <NgayMuon>2021-02-03</NgayMuon>
        <TaiCho>Tại chỗ</TaiCho>
    </ChiTietMuon>
    <ChiTietMuon>
        <MaThe>PM0001</MaThe>
        <MaSach>A10101</MaSach>
        <NgayMuon>2019-03-05</NgayMuon>
        <NgayTra>2019-04-02</NgayTra>
        <TaiCho>Về nhà</TaiCho>
    </ChiTietMuon>
    <ChiTietMuon>
        <MaThe>PM0002</MaThe>
        <MaSach>A10103</MaSach>
        <NgayMuon>2021-02-03</NgayMuon>
        <TaiCho>Tại chỗ</TaiCho>
    </ChiTietMuon>
    <ChiTietMuon>
        <MaThe>PM0002</MaThe>
        <MaSach>A10104</MaSach>
        <NgayMuon>2021-04-03</NgayMuon>
        <NgayTra>2021-04-09</NgayTra>
        <TaiCho>Về nhà</TaiCho>
    </ChiTietMuon>
    <ChiTietMuon>
        <MaThe>PM0004</MaThe>
        <MaSach>A10105</MaSach>
        <NgayMuon>2019-05-03</NgayMuon>
        <TaiCho>Tại chỗ</TaiCho>
    </ChiTietMuon>
    
    <LePhi>
        <MaThe>PM0001</MaThe>
        <Nam>2021</Nam>
        <LePhi>80000</LePhi>
    </LePhi>
    <LePhi>
        <MaThe>PM0002</MaThe>
        <Nam>2020</Nam>
        <LePhi>90000</LePhi>
    </LePhi>
    <LePhi>
        <MaThe>PM0003</MaThe>
        <Nam>2021</Nam>
        <LePhi>50000</LePhi>
    </LePhi>
    <LePhi>
        <MaThe>PM0004</MaThe>
        <Nam>2021</Nam>
        <LePhi>100000</LePhi>
    </LePhi>
    <LePhi>
        <MaThe>PM0005</MaThe>
        <Nam>2021</Nam>
        <LePhi>95000</LePhi>
    </LePhi>
</QLMS>
