=== NguyenThanhLanh/XML_Technology/BTChuong7_XSLT/BT3/MonHoc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="QLMH">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MonHoc" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaMH" minOccurs="1" maxOccurs="1" type="xs:string"/>
                            <xs:element name="TenMH" minOccurs="1" maxOccurs="1" type="xs:string"/>
                            <xs:element name="SoGio" minOccurs="1" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="4"/>
                                        <xs:maxInclusive value="48"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== NguyenThanhLanh/XML_Technology/BTChuong7_XSLT/BT3/MonHoc.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="MonHoc.xsl"?>
<QLMH xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/D:/CongNghe_XML_VaUngDung/BTChuong7_XSLT/BT3/MonHoc.xsd">
    <MonHoc>
        <MaMH>CSDL</MaMH>
        <TenMH>Cơ sở dữ liệu</TenMH>
        <SoGio>30</SoGio>
    </MonHoc>
    <MonHoc>
        <MaMH>MCB</MaMH>
        <TenMH>Mạng căn bản</TenMH>
        <SoGio>30</SoGio>
    </MonHoc>
    <MonHoc>
        <MaMH>THDC</MaMH>
        <TenMH>Tin học đại cương</TenMH>
        <SoGio>45</SoGio>
    </MonHoc>
    <MonHoc>
        <MaMH>THVP</MaMH>
        <TenMH>Tin học văn phòng</TenMH>
        <SoGio>45</SoGio>
    </MonHoc>
    <MonHoc>
        <MaMH>XLA</MaMH>
        <TenMH>Xử lý ảnh</TenMH>
        <SoGio>45</SoGio>
    </MonHoc>
</QLMH>
