=== NguyenThanhLanh/XML_Technology/BTChuong7_XSLT/BT4/KetQua.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="QLKQ">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="KetQua" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaSV" minOccurs="1" maxOccurs="1" type="xs:string"/>
                            <xs:element name="MaMH" minOccurs="1" maxOccurs="1" type="xs:string"/>
                            <xs:element name="DiemThi">
                                <xs:simpleType>
                                    <xs:restriction base="xs:double">
                                        <xs:maxInclusive value="10"/>
                                        <xs:minInclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== NguyenThanhLanh/XML_Technology/BTChuong7_XSLT/BT4/KetQua.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="KetQua.xsl"?>
<QLKQ xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/D:/CongNghe_XML_VaUngDung/BTChuong7_XSLT/BT4/KetQua.xsd">
    <KetQua>
        <MaSV>sv01</MaSV>
        <MaMH>THDC</MaMH>
        <DiemThi>10</DiemThi>
    </KetQua>
    <KetQua>
        <MaSV>sv01</MaSV>
        <MaMH>THVP</MaMH>
        <DiemThi>9.5</DiemThi>
    </KetQua>
    <KetQua>
        <MaSV>sv02</MaSV>
        <MaMH>THDC</MaMH>
        <DiemThi>9</DiemThi>
    </KetQua>
    <KetQua>
        <MaSV>sv02</MaSV>
        <MaMH>THVP</MaMH>
        <DiemThi>8</DiemThi>
    </KetQua>
    <KetQua>
        <MaSV>sv03</MaSV>
        <MaMH>THDC</MaMH>
        <DiemThi>7</DiemThi>
    </KetQua>
    <KetQua>
        <MaSV>sv03</MaSV>
        <MaMH>THVP</MaMH>
        <DiemThi>4.5</DiemThi>
    </KetQua>
</QLKQ>
